stages:
  - test
  - build
  - scan
  - deploy

variables:
  REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/attack-threat-modeling"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  GITOPS_PROJECT_PATH: "miranda/miranda-gitops.git"

# --- 1. Test Stage ---
unit-tests:
  stage: test
  image: python:3.6-slim-buster
  script:
    - echo "No tests"
    # - pip install -r requirements.txt
    # - pytest
  allow_failure: true


# --- 2. Build Stage ---
build-and-push:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo "Building Attack Threat Modeling image with Kaniko..."
    - mkdir -p /kaniko/.docker
    - |
      cat > /kaniko/.docker/config.json << EOF
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "username": "$DOCKERHUB_USERNAME",
            "password": "$DOCKERHUB_TOKEN"
          },
          "registry.gitlab.com": {
            "username": "gitlab-ci-token",
            "password": "$CI_JOB_TOKEN"
          }
        }
      }
      EOF
    - >
      /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --destination "$REGISTRY_IMAGE:$IMAGE_TAG"
      --destination "$REGISTRY_IMAGE:latest"
      --skip-tls-verify

# --- 3. Scan Stage ---
scan-image:
  stage: scan
  image: aquasec/trivy:latest
  needs: ["build-and-push"]
  allow_failure: true
  script: |
    echo "Scanning image  $REGISTRY_IMAGE:$IMAGE_TAG"
    trivy image \
        --exit-code 1 \
        --severity CRITICAL \
        --username "$CI_REGISTRY_USER" \
        --password "$CI_REGISTRY_PASSWORD" \
        "$REGISTRY_IMAGE:$IMAGE_TAG"

# --- 4. Deploy Stage ---
update-gitops-main:
  stage: deploy
  image: alpine:latest
  needs: ["build-and-push"]
  variables:
    GIT_USER_NAME: "GitLab CI Bot"
    GIT_USER_EMAIL: "gitlab-ci@example.com"
  before_script:
    - apk add --no-cache git ca-certificates
    - update-ca-certificates
    - git config --global user.name "$GIT_USER_NAME"
    - git config --global user.email "$GIT_USER_EMAIL"
    - 'if [ -z "${GITOPS_PAT:-}" ]; then echo "ERROR: GITOPS_PAT is empty or not set."; exit 1; fi'
  script:
    - GITOPS_REPO_HTTPS="https://oauth2:${GITOPS_PAT}@${CI_SERVER_HOST}/${GITOPS_PROJECT_PATH}"
    - git clone "$GITOPS_REPO_HTTPS" miranda-gitops
    - cd miranda-gitops
    - 'sed -i "s|\(image: .*/attack-threat-modeling:\).*|\1$IMAGE_TAG|" attack-threat-modeling/deployment-att.yaml'
    - git add attack-threat-modeling/deployment-att.yaml
    - git diff --cached --quiet && echo "No image tag changes detected." && exit 0
    - 'git commit -m "ci: update attack-threat-modeling image tag to $IMAGE_TAG"'
    - git push origin HEAD:main
    