apiVersion: apps/v1
kind: Deployment
metadata:
  name: attack-threat-modeling
  namespace: polito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attack-threat-modeling
  template:
    metadata:
      labels:
        app: attack-threat-modeling
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: attack-threat-modeling
          image: registry.intra.miranda.onesource.pt/miranda/attack-threat-modeling/attack-threat-modeling:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_APP
              value: app.py
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: attack-threat-modeling
  namespace: polito
spec:
  selector:
    app: attack-threat-modeling
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attack-threat-modeling
  namespace: polito
spec:
  ingressClassName: nginx
  rules:
    - host: attack-threat-modeling.intra.miranda.onesource.pt
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: attack-threat-modeling
                port:
                  number: 5001